### ISSUE TITLE
Add optional instructions to deploy Kibana

### ISSUE THREAD

**Issue by reedfrancis** [pires/kubernetes-elasticsearch-cluster#101]
Your project is amazing for setting up elasticsearch on kubernetes, but it would be great to have the yaml files for setting up kibana also. Could this be added to the project?

**Comment by pires** [comment]
I'm open to review PRs.

**Comment by cfontes** [comment]
Here is my suggestion

https://github.com/pires/kubernetes-elasticsearch-cluster/pull/111

**Comment by pires** [comment]
Fixed! Thanks @cfontes.
