### ISSUE TITLE
es-data not join to master

### ISSUE THREAD

**Issue by timchenxiaoyu** [pires/kubernetes-elasticsearch-cluster#103]
NETWORK_HOST=_eth0_

publish_address {172.32.10.164:9300}, bound_addresses {172.32.10.164:9300}, {[fe80::6409:29ff:fe30:f675]:9300}
myesdb/l3-bVMBYQbqJSF_DvGubaA
waited for 30s and no initial state was set by the discovery
started

data node does join to master

**Comment by timchenxiaoyu** [comment]
NETWORK_HOST=_eth0_

**Comment by pires** [comment]
This can't be seen as an issue as there's no meaningful information.
