### ISSUE TITLE
elasticsearch fails due to IPv6

### ISSUE THREAD

**Issue by drobinson123** [pires/kubernetes-elasticsearch-cluster#105]
Intermittent failures occur when starting elasticsearch masters (and possible other components). The failures occur when the local network interface has both IPv4 and IPv6 addresses and elasticsearch attempts to bind to the IPv6 address first. If the IPv4 address is chosen first elasticsearch starts correctly.

Attached are two sets of logs, one showing a [successful startup](https://github.com/pires/kubernetes-elasticsearch-cluster/files/1106878/success.txt) and the other showing a [failure](https://github.com/pires/kubernetes-elasticsearch-cluster/files/1106879/failed.txt). The line of interest contains 'binding server bootstrap to' -- note the order of the IPs.

The workaround was to set `NETWORK_HOST` to `_eth0:ipv4_` so only IPv4 is considered. You may want to add this note to the README.

**Comment by pires** [comment]
Sounds reasonable. Care to open a PR?
