### ISSUE TITLE
Add PodDisruptionBudget

### ISSUE THREAD

**Issue by abh** [pires/kubernetes-elasticsearch-cluster#110]
It seems like it'd be useful to add a PodDisruptionBudget to the manifest files, at least for the master nodes.

**Comment by pires** [comment]
I'm interested in reviewing PRs.

**Comment by deimosfr** [comment]
Feel free to contribute to #133

**Comment by deimosfr** [comment]
I think this could be closed as merged now

**Comment by pires** [comment]
Fixed in #133.
