### ISSUE TITLE
es-curator.yaml failed to run on k8s 1.7.3

### ISSUE THREAD

**Issue by gensmusic** [pires/kubernetes-elasticsearch-cluster#112]
`kubectl create -f es-curator.yaml`
And I got
```
error: error validating "es-curator.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by pires** [comment]
Most probably, you don't have your Kubernetes cluster properly configured to support cron jobs. See https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#prerequisites.
