### ISSUE TITLE
elasticsearch is publicly accessible over the web by default?

### ISSUE THREAD

**Issue by bw2** [pires/kubernetes-elasticsearch-cluster#114]
When deploying configs to GKE, the "client" service load balancer is automatically assigned an external IP address, making the entire cluster accessible over the public internet by default. 

https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-svc.yaml#L9

**Comment by pires** [comment]
That is correct. That is the default GKE behavior for services of type LoadBalancer. My suggestion is  either to set the `clusterIP` as `None` or annotate your service with ```
[...]
metadata:
    name: my-service
    annotations:
        cloud.google.com/load-balancer-type: "internal"
[...]
```

**Comment by bw2** [comment]
It be worth rewording this part of the README
```
Don't forget that services in Kubernetes are only acessible from containers in the cluster. For different behavior one should configure the creation of an external load-balancer. While it's supported within this example service descriptor, its usage is out of scope of this document, for now.
```
- to me it reads like "everything is private by default, but can be made public through steps not included in this repo."

**Comment by pires** [comment]
Feel free to open a PR to make it clearer to everyone, not just GKE users.

**Comment by pires** [comment]
Wait, wait.. someone just made me realize the default service type is now `ClusterIP`!
