### ISSUE TITLE
Kibana: { statusCode: 404, error: "Not Found" }

### ISSUE THREAD

**Issue by oavioz** [pires/kubernetes-elasticsearch-cluster#117]
Thanks for amazing deployment setting up elasticsearch on kubernetes!
I've just set up this repo exsample elasticsearch working properly. kibana not. getting error: { statusCode: 404, error: "Not Found" }

https://<API_SERVER_URL>/api/v1/proxy/namespaces/default/services/kibana:5601

Response:
404, error: "Not Found" }

This is my deployment status:

NAME                          CLUSTER-IP     EXTERNAL-IP     PORT(S)          AGE
svc/elasticsearch             10.0.4.253     23.100.11.242   9200:31517/TCP   1h
svc/elasticsearch-discovery   10.0.116.196   <none>          9300/TCP         1h
svc/kibana                    10.0.212.252   40.68.94.216    80:30710/TCP     54m
svc/kubernetes                10.0.0.1       <none>          443/TCP          2h

NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/es-client   2         2         2            2           1h
deploy/es-data     2         2         2            2           1h
deploy/es-master   3         3         3            3           1h
deploy/kibana      1         1         1            1           55m

NAME                            READY     STATUS    RESTARTS   AGE
po/es-client-3209164131-brkqk   1/1       Running   0          1h
po/es-client-3209164131-p8dhr   1/1       Running   0          1h
po/es-data-4279095385-b5nbs     1/1       Running   0          1h
po/es-data-4279095385-pw1rq     1/1       Running   0          1h
po/es-master-3462269314-bscpn   1/1       Running   0          1h
po/es-master-3462269314-l6djz   1/1       Running   0          1h
po/es-master-3462269314-mrld0   1/1       Running   0          1h
po/kibana-3831579333-2bd1p      1/1       Running   0          55m

Any help?

Many Thanks,
Oshik

**Comment by pires** [comment]
Try `https://<API_SERVER_URL>/api/v1/proxy/namespaces/default/services/kibana` instead.

**Comment by oavioz** [comment]
Hi Pires,

Thanks for response.

Still not work. any other options?

Many thanks,
Oshik.

[image: Inline image 1]

**Comment by andriosr** [comment]
It looks like your service is exposing port `80` and not `5601`, try removing the port form your URL and also make sure the name of your service is `kibana`

**Comment by snaimuddin** [comment]
Hi i deployed elasticsearch and kibana in marathon (cloud)
Elasticsearch is running,when i see in kibana unable to connect to elasticsearch..
i used environment variable as ELASTICSEARCH_URL="mydomain.elasticsearch"

why it is ?
any

**Comment by bevinhex** [comment]
This issue still persist, why is this closed?
