### ISSUE TITLE
{ statusCode: 404, error: "Not Found" } - Still not work

### ISSUE THREAD

**Issue by oavioz** [pires/kubernetes-elasticsearch-cluster#118]
Hi Pires,

Thanks for response.

Still not work. any other options?

Many thanks,
Oshik.

**Comment by elic9** [comment]
Hi,

if You are referring to kibana, just remove these lines from kibana.yml

```
- name: SERVER_BASEPATH
  value: /api/v1/proxy/namespaces/default/services/kibana
```

**Comment by pires** [comment]
Fixed by https://github.com/pires/kubernetes-elasticsearch-cluster/pull/123
