### ISSUE TITLE
Any stress tests?

### ISSUE THREAD

**Issue by mkliu** [pires/kubernetes-elasticsearch-cluster#12]
I'm wondering have you run this in production with some serious data to stress test it? 

I'm thinking about doing the same thing but worried about nodes going up&down and cause ElasticSearch moving shards around. 

Kubernetes is designed for micro services which can die any time, but for Elasticsearch clusters which have a big amount of data, that would be disastrous.

**Comment by pires** [comment]
You are right in the sense Kubernetes is not yet prepared for stateful services that need to store persistent data.

This is an exercise and I don't use it in production.
