### ISSUE TITLE
Deploying with Helm Permission denied (publickey)

### ISSUE THREAD

**Issue by oavioz** [pires/kubernetes-elasticsearch-cluster#122]
Hi,

git clone of "git@github.com:clockworksoul/helm-elasticsearch.git" is not allowed. Permission denied (publickey).

Can you update please?

Thanks.

**Comment by oavioz** [comment]
Thanks Pires! i saw you removed -  type: LoadBalancer on both, kiban and elastic service. ant reason?

Thanks

**Comment by pires** [comment]
Yes. Kubernetes integration with cloud-providers, such as GKE, would create Internet-facing load-balancers by default.

**Comment by oavioz** [comment]
Thanks Pires. for me , i'm using azure  - ACS. so it is not a default. 
By the way, on kibana services it was an issues about "accessing to kibana -  #119
I saw the solution was to comment both, #        - name: SERVER_BASEPATH
#          value: /kibana:5601.

So now it is Ok?

Thanks!
