### ISSUE TITLE
Can't access elasticsearch from Kibana

### ISSUE THREAD

**Issue by elic9** [pires/kubernetes-elasticsearch-cluster#125]
Hi,

When I access Kibana and trying to execute any request to ES (e.g. 
```
POST /my_index/my_book/1
{
  "title": "test book"
})
```

I get timeout, when checking the logs, I can see an error 

> [2017-09-10T21:04:21,998][WARN ][r.suppressed             ] path: /.kibana/config/_search, params: {index=.kibana, type=config}
> org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

I don't manage to understand, I can see that all my pods are up and running, however, when I manage to execute GET /_cluster/health?pretty
I could see that not all shards are available, but I don't manage to execute this API again.

Any ideas what can be wrong or what I can do to isolate the problem?

Thank you

**Comment by elic9** [comment]
I did some more checks, I can't access elastic search, I get failures.

Executing API http://<host>:9200/_cluster/health?pretty

I get the following:

> {
>   "cluster_name" : "elasticsearch-rtds-dev",
>   "status" : "yellow",
>   "timed_out" : false,
>   "number_of_nodes" : 3,
>   "number_of_data_nodes" : 1,
>   "active_primary_shards" : 6,
>   "active_shards" : 6,
>   "relocating_shards" : 0,
>   "initializing_shards" : 0,
>   "unassigned_shards" : 6,
>   "delayed_unassigned_shards" : 0,
>   "number_of_pending_tasks" : 0,
>   "number_of_in_flight_fetch" : 0,
>   "task_max_waiting_in_queue_millis" : 0,
>   "active_shards_percent_as_number" : 50.0
> }

For some reason there is a problem with the shards, how do you define your shards?

Thanks

**Comment by magicalbanana** [comment]
Any help on this @pires?

**Comment by pires** [comment]
@elic9 you only have 1 data-node.

@magicalbanana you're probably having the same issue as elic9. If you don't have enough data-nodes for your replication configuration, you'll have unassigned shards.

**Comment by magicalbanana** [comment]
@pires how do I add more data-notes?

**Comment by pires** [comment]
Increase the number of data-node replicas:
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-data.yaml#L9
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/stateful/es-data-stateful.yaml#L10
