### ISSUE TITLE
path.repo for snapshots

### ISSUE THREAD

**Issue by sybnex** [pires/kubernetes-elasticsearch-cluster#139]
Would it be possible to add path.repo or 
path:
  repo: e.g. /backup

to the elasticsearch.yml? I don't want to remount this directory.

Reason: for snapshots

**Comment by Globegitter** [comment]
Just running into the same issue - on top of that I want to add the aws config. I know some projects like nginx ingress allow for custom config snippets to be added. It might just be as simple as adding an env variable at the end of the elasticsearch.yml, such as `${CUSTOM_CONFIG_SNIPPET}` and defaulting that to empty.

**Comment by pires** [comment]
Why not use a ConfigMap and mount it where Elasticsearch expects it to be?

**Comment by Globegitter** [comment]
@pires I guess I did not think about that as I only want to modify one file and not the whole folder - but I guess that is actually possible now with k8s using `subPath`, so fair point.

**Comment by sybnex** [comment]
@Globegitter I'm not sure `subPath `acts like this => [https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath]

@pires The problem is, that k8 overmounts the whole directory. You are not able to mount a single file into a existing directory like in Docker atm. 

For my specific case, I've wrote a new Dockerfile which includes your Image.

**Comment by Centro1993** [comment]
Same Issue here. And since the Readme.MD states:

> Providing one's own version of the images automatically built from this repository will not be supported. This is an optional step. One has been warned.

I would greatly prefer have the line
    `path.repo=/data/repo`
added to the docker image config.

**Comment by pires** [comment]
I'll look into it tomorrow.

**Comment by Centro1993** [comment]
Great! I was about to commit the changes myself, but noticed that @ruediste actually already commited the neccessary changes in pires/docker-elasticsearch-kubernetes#48, but never bothered to changing his Email and therefore the pull request has not been accepted.

**Comment by pires** [comment]
That PR is not in a good shape. Also, it's in the wrong repo.

**Comment by pires** [comment]
Feel free to open a PR to adopt the changes in https://github.com/pires/docker-elasticsearch/blob/34045fe6f66528a10ecf137569f1f30bd1f70789/README.md#backup. I will release a new image as soon as there's a new Elasticsearch release.
