### ISSUE TITLE
Unknown object type for es-curator,  k8s 1.8

### ISSUE THREAD

**Issue by z1nkum** [pires/kubernetes-elasticsearch-cluster#158]
Hi,

I was surprised when trying create curator CronJob:

```# kubectl create -f es-curator.yaml```

error: error validating "es-curator.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"batch", Version:"v2alpha1", Kind:"CronJob"}; if you choose to ignore these errors, turn validation off with --validate=false

It's because of https://github.com/kubernetes/kubernetes/issues/41039 - so, if you try it with 1.8, change

```apiVersion: batch/v2alpha1``` to ```apiVersion: batch/v1beta1```

**Comment by pires** [comment]
Good catch.
