### ISSUE TITLE
GCS Plugin: Repository type [gcs] does not exist

### ISSUE THREAD

**Issue by tutoring** [pires/kubernetes-elasticsearch-cluster#159]
The instructions for installing the GCS plugin specify that after adding: 
- name: "ES_PLUGINS_INSTALL"
   value: "repository-gcs"

...to the relevant deployments, then GCS bucket storage should be accessible, but it does not seem to be. The installation instructions on the ES website call for restarting the nodes and I'm not sure if that is part of the cause or not.

**Comment by pires** [comment]
We're installing the plug-ins before Elasticsearch starts so there's no need for restarting Elasticsearch.

Please, follow the [official instructions](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-gcs-usage.html) for the respective plug-in. If it doesn't work, you should reach to the Elasticsearch project.

**Comment by tutoring** [comment]
I figured a pre-start installation was the case. Given the error message saying that the repository type does not exist, I wasn't totally sure though. 

I'll try to reproduce this a few times to ensure it isn't just user error on my part. What you have provided with this repo is fantastic. Thank you for that.

**Comment by pires** [comment]
Thank you for taking the time so say "thank you" :)
