### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by DTherHtun** [pires/kubernetes-elasticsearch-cluster#168]
> kubectl logs po/es-client-5dfd67955f-8lstl
Error from server: Get https://172.17.8.103:10250/containerLogs/default/es-client-5dfd67955f-8lstl/es-client: net/http: TLS handshake timeout

**Comment by pires** [comment]
This is a problem with your Kubernetes cluster setup since you can't access the secure kubelet API endpoint.
