### ISSUE TITLE
Clarity on X-Pack (#102)

### ISSUE THREAD

**Issue by kleuf** [pires/kubernetes-elasticsearch-cluster#187]
Firstly, thank you for all the work you do, big fan.

Secondly sorry for opening this can of worms again.

So, I saw you posted about using elasticsearch:6.2.3_1 that includes X-Pack, which brings me to my question, which, if available, images should i use to build a full stack that uses X-Pack, this being Elasticsearch, Logstash and Kibana.

I used the image for Elasticsearch, "quay.io/pires/docker-elasticsearch-kubernetes:6.2.3_1" but when i pull the "pires/logstash" and "docker.elastic.co/kibana/kibana:6.2.3" images, the logs are filled with X-Pack issues.

Any feedback will be appreciated in this regard, even only a reply with the images i should use or config I can change.

Thank you

**Comment by pires** [comment]
`pires/docker-logstash` is very old. TBH I don't use this setup anymore, so I can't be of help as we speak.
