### ISSUE TITLE
Use recommended node layout

### ISSUE THREAD

**Issue by rocketraman** [pires/kubernetes-elasticsearch-cluster#190]
This does not appear to use the [recommended](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-node.html) node layout as stated in the README.

The recommended layout separates ingestion nodes from client/data nodes, and it does not separate client and data nodes -- the nodes receiving query traffic are the same nodes that have data.

**Comment by pires** [comment]
Well, you are most probably right. This repo comes from a different time. I'm happy to review PRs.
