### ISSUE TITLE
Cannot launch the ES cluster because of insufficient CPU

### ISSUE THREAD

**Issue by duchnguyen** [pires/kubernetes-elasticsearch-cluster#195]
Hi,

I checked-out the code to my local and ran below commands in order 

<pre>
kubectl create -f es-discovery-svc.yaml
kubectl create -f es-svc.yaml
kubectl create -f es-master.yaml
kubectl create -f es-client.yaml
kubectl create -f es-data.yaml
</pre>

-> couldn't launch the ES cluster because of insufficient CPU as below 

Note that my Kubernetes Cluster has 3 nodes (machine type for each node : n1-standard-1 (1 vCPU, 3.75 GB memory). 

The issue is the same when I change 
- replicas=1 for each yaml file 
- set ES_JAVA_OPTS = -Xms2g -Xmx2g

![es-insufficient-cpu](https://user-images.githubusercontent.com/38968649/41346413-9f4b0a18-6f30-11e8-9ea8-8e9586493a39.png)

![es-insufficient-cpu-02](https://user-images.githubusercontent.com/38968649/41346416-a00d0be0-6f30-11e8-8333-74eca8d77568.png)

Thanks,
Duc

**Comment by pires** [comment]
Since no CPU requests are made, I don't know what's going on.

**Comment by duchnguyen** [comment]
Hi Pires,

> Since no CPU requests are made, I don't know what's going on.

Can you please tell more detail about this? How can I fix it? I don't change anything related to resources.limits.cpu configuration.

Thanks,
Duc

**Comment by pires** [comment]
Limits is not the problem here, since it guarantees that your pod will not consume more than 1000ms of cpu per second. But we don't define Requests, so I don't know why Kubernetes complains there's not enough CPU.

For more info, please read https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/.
