### ISSUE TITLE
How would we use persistentDisk?

### ISSUE THREAD

**Issue by jasonkuhrt** [pires/kubernetes-elasticsearch-cluster#2]
The Kubernetes `volumes` docs have information about the currently supported source types:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md#gcepersistentdisk

What we want is the Elasticsearch cluster to have a data node that has *lots* of disk space. We need a persistent disk for this. The only one supported right now is `persistentDisk `. But there is a limitation with it, right now:

> avoid creating multiple pods that use the same Volume
if multiple pods refer to the same Volume and both are scheduled on the same machine, regardless of whether they are read-only or read-write, then the second pod scheduled will fail.
Replication controllers can only be created for pods that use read-only mounts.

This means that your pattern of a data node behind a `replicationController` would fail because by design it tries to replicate multiple pods sharing a disk. That works with the current `emptyDir` setup but that same setup fails the use-case of needing a *persistent* and *large* disk.

My suggestion right now is to limit the `replicationController` replica count to `1` and switch over to use a GCE PD.

**Comment by pires** [comment]
I have a workaround for this that is related to https://github.com/GoogleCloudPlatform/kubernetes/issues/3945 in the sense that we can limit the number of Elasticsearch data-nodes, which I think are the only ones needing to persist data, running on a minion. Sorry, node :-p

**Comment by jasonkuhrt** [comment]
> we can limit the number of Elasticsearch data-nodes

Yes, by simply using `replicas: 1`. In what sense does GoogleCloudPlatform/kubernetes#3945 factor in here? Your issue seems a lot fancier because its about smart resource allocation wherein e.g. its impossible to schedule more than one pod per machine because e.g. it doesn't make sense for throughput.

So while we have  "solution" with `replicas: 1` its a very limiting one of course because we cannot scale that pod. The `replicationController` part is a lie for now : )

**Comment by pires** [comment]
I think we can set the number of replicas we wish. We just need a couple
things:
* nodeSelector for pods to be scheduled in specific machines marked with
predefined labels
* set data-node pods resources (like ram) to match the VM allocated ram in
a way that said machine can't hold more than one data-node.

This way you can have multiple data-nodes and as many replicas as machines
available.

**Comment by jasonkuhrt** [comment]
Ok, I'm curious to see what you will come up with. I'm trying things on my fork and will share anything useful.

**Comment by jasonkuhrt** [comment]
You can see some issues I am running into with `PD` here: https://github.com/GoogleCloudPlatform/kubernetes/issues/4052

**Comment by mlamina** [comment]
Has there been any solution to this problem? I can't figure out how to provide persistent storage for my Elasticsearch cluster, which makes it useless :(

**Comment by pires** [comment]
@mlamina this is not a bug so it doesn't need to be fixed. This is something that you, as an user, should change to match your environment. I can't force a volume setup other than the `emptyDir` nor can I support every possibility in existence. I urge you to learn about Kubernetes volume plug-ins and adapt the data node `replicationController` as you see fit.

**Comment by mlamina** [comment]
I understand that! Do you have a recommendation which scales with the ReplicationController? GCE PersistentDisk doesn't seem to work and I feel like setting up a GlusterFS cluster seems to be overkill?

**Comment by pires** [comment]
There are more plug-ins than those two. Choose what's best to your use-case.

**Comment by sgrimee** [comment]
In case someone lands here looking for a workaround, I used the suggestion from @davidopp in  kubernetes/kubernetes#3945: set a hostPort for the datanode pod. That prevents two instances of from being scheduled on the same node.

        ports:
        - containerPort: 65535
          name: anti-affinity
          hostPort: 65535

It is sub optimal because the anti-affinity port number needs to be unique for the pod template, but it avoids the need to match pod resources to node resources (I still want to run other pods on the node)

**Comment by pires** [comment]
You can also try integration with [`flocker`](https://github.com/ClusterHQ/flocker).

**Comment by snehacapoor** [comment]
I agree with you
