### ISSUE TITLE
Certificates error

### ISSUE THREAD

**Issue by AlexRezid** [pires/kubernetes-elasticsearch-cluster#21]
Hi,

I'm not sure if it's a bug or not, but following the readme doc give me an error : 
`[2015-09-29 15:50:57,570][ERROR][io.fabric8.kubernetes.api.KubernetesFactory] Specified CA certificate file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt does not exist or is not readable`

Followed by lot of 
`Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

What did I forgot to get this certificate working ? 

Thanks for your help

Alex

**Comment by pires** [comment]
@AlexRezid that's a problem with your Kubernetes installation. Can you list the contents of `/var/run/secrets/kubernetes.io/serviceaccount` on the nodes you're trying to deploy this example?

**Comment by AlexRezid** [comment]
@pires The folder does not exist on the master nor the nodes....

    core@nodeXXXX ~ $ sudo ls /var/run/secrets
    ls: cannot access /var/run/secrets: No such file or directory

kubernetes v1.0.3
Installed from : https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md

**Comment by pires** [comment]
Sorry, it should exist **only** on the pods themselves not the nodes.

**Comment by pires** [comment]
@AlexRezid unfortunately said tutorial doesn't support certificates and it's about to be deprecated in favor of https://coreos.com/kubernetes/docs/latest/getting-started.html. Please use that or https://github.com/pires/kubernetes-vagrant-coreos-cluster.

**Comment by AlexRezid** [comment]
@pires Thanks, will have a look on this.
