### ISSUE TITLE
Deprecated service

### ISSUE THREAD

**Issue by Nalum** [pires/kubernetes-elasticsearch-cluster#218]
In the `README.md` the Kubernetes `Service` file below is listed as a required resource in the setup guide:
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/3053cdda99cdc6f67e6fee892119929d701b4e7e/es-svc.yaml#L1-L15
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/3053cdda99cdc6f67e6fee892119929d701b4e7e/README.md#L67-L81

Then when setting up the data nodes using the `StatefulSet` rather than the `Deployment` the `README.md` again states to use the above `Service`.
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/3053cdda99cdc6f67e6fee892119929d701b4e7e/stateful/README.md#L9-L24

There doesn't appear to be anything mentioned about the below `Service` and I was just wondering if this is something that was missed or if it's not required?
https://github.com/pires/kubernetes-elasticsearch-cluster/blob/3053cdda99cdc6f67e6fee892119929d701b4e7e/stateful/es-data-svc.yaml#L1-L15

Aside from the `Service` name the difference between them is the port that is exposed.

**Comment by pires** [comment]
You're right, it seems to be leftovers from a distant past. I'll remove it, thanks.
