### ISSUE TITLE
Using data volume for data pods

### ISSUE THREAD

**Issue by codingwithoutcomments** [pires/kubernetes-elasticsearch-cluster#22]
How would one go about using attached data volumes instead of storing data on the instance?

**Comment by pires** [comment]
@codingwithoutcomments it's as easy as [set-up one volume](http://kubernetes.io/v1.1/docs/user-guide/volumes.html) and mount it at https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-data-rc.yaml#L50.
