### ISSUE TITLE
Missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec

### ISSUE THREAD

**Issue by paulavijit** [pires/kubernetes-elasticsearch-cluster#220]
Executing:
kubectl apply -f es-master-stateful.yaml

Results in error:
error: error validating "es-master-stateful.yaml": error validating data: [ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec, ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by charlenezheng** [comment]
It can be solved when you add these labels into your yaml file.
For example:
for "missing required field 'selector' ": 
you can add selector with matchLabels, like:
  `selector:
      matchLabels:
          app: something`
