### ISSUE TITLE
Why this project if we have it in an oficial ElasticSearch as Helm package?

### ISSUE THREAD

**Issue by alexsandro-xpt** [pires/kubernetes-elasticsearch-cluster#238]

**Comment by rewt** [comment]
For one thing, this project makes it super simple to install plugins...when working.

**Comment by pires** [comment]
Why this question in the first place? What's the problem with having more than one way to solve a problem?

I keep being asked about this project vs the operator or vs the helm chart. Thing is, this project was already here long before there was any operator or helm chart. And funny enough, both of those projects fed from this project.

Choose whatever fits your needs. If nothing fits, feel free to contribute your own or to the existing efforts.

**Comment by alexsandro-xpt** [comment]
@pires Is exactly this point `Choose whatever fits your needs.` This question is exactly about that. We unknown what of both fits what we need and we need to know those differences to make a right choose.

If you can explain for us, thank you.
