### ISSUE TITLE
How to prevent ES from being exposed to the internet?

### ISSUE THREAD

**Issue by haizaar** [pires/kubernetes-elasticsearch-cluster#29]
More of a question than an issue - `es-svc.yaml` defines load balancer service, which in Google Cloud automatically gets assigned a public address and is opened to incoming traffic from the internet. Is there a way to avoid exposing it to the internet?

**Comment by pires** [comment]
Just remove the load-balancer attribute.

**Comment by haizaar** [comment]
I knew it was something trivial. Thanks!
