### ISSUE TITLE
Add Sense UI?

### ISSUE THREAD

**Issue by KyleAMathews** [pires/kubernetes-elasticsearch-cluster#30]
Not entirely this makes sense (new to Kubernetes and somewhat to ES) but it'd be cool if you could add the Sense plugin and use `kubectl proxy` to be able to live query production data.

Thoughts?

**Comment by pires** [comment]
You can do it with your own images that use `quay.io/pires/docker-elasticsearch-kubernetes` as base image. I don't think it would make sense to add that here and force _everyone_ to use it. I've never used, for instance.

**Comment by KyleAMathews** [comment]
Thanks
