### ISSUE TITLE
Rolling update in data node

### ISSUE THREAD

**Issue by thuandt** [pires/kubernetes-elasticsearch-cluster#37]
I'm use data node with  `gcePersistentDisk` as storage.
I can rolling update `es-master` and `es-client` without problem, but `kubectl` stuck when rolling update in `es-data`.
Can you tell me how to rolling update in `data node`?

Thanks

**Comment by pires** [comment]
You should look into your Kubernetes cluster logs to understand why it isn't rolling the new containers. Did you set your own resource limits?

**Comment by thuandt** [comment]
I don't put any resources limits.
Here is some logs:
```
kubectl rolling-update es-client --image=xxx.gcr.io/xxxx/elasticsearch:2.3.1                                                                                          [112/696]
Created es-client-10263f5d912933f33bf50a8017911b2c
Scaling up es-client-10263f5d912933f33bf50a8017911b2c from 0 to 1, scaling down es-client from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
Scaling es-client-10263f5d912933f33bf50a8017911b2c up to 1
Scaling es-client down to 0
Update succeeded. Deleting old controller: es-client
Renaming es-client-10263f5d912933f33bf50a8017911b2c to es-client
replicationcontroller "es-client" rolling updated
```
But `es-data` stuck and timeout:
```
kubectl rolling-update es-data --image=xxx.gcr.io/xxx/elasticsearch:2.3.1
Created es-data-e4a1dd6edcfee4597836edc3ecb07ad8
Scaling up es-data-e4a1dd6edcfee4597836edc3ecb07ad8 from 0 to 1, scaling down es-data from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
Scaling es-data-e4a1dd6edcfee4597836edc3ecb07ad8 up to 1
error: timed out waiting for any update progress to be made
```

`xxx.gcr.io/xxx/elasticsearch:2.3.1` image i build for myself, based your image just added more plugin.

**Comment by pires** [comment]
Again, you should look at your Kubernetes cluster logs. This doesn't seem an issue related to this project.
