### ISSUE TITLE
I wish I could use my own Docker image

### ISSUE THREAD

**Issue by ScubaDrew** [pires/kubernetes-elasticsearch-cluster#38]
Why can we not create our own Docker image for this?

"Providing your own version of the images automatically built from this repository will not be supported."

Thanks!
Drew

**Comment by pires** [comment]
@ScubaDrew I never said you couldn't but just that I won't support it. Makes sense, right?

**Comment by ScubaDrew** [comment]
@pires Absolutely makes sense. I thought you were saying we could _not_ provide out own images.

The reason I thought this is, when I inspect your Dockerfile, I see the base is:

`FROM **quay.io/pires**/docker-elasticsearch:2.3.2` versus pulling from the official elasticsearch:2.3.2 on hub.docker.com

Are the equivalent?

**Comment by pires** [comment]
Nop. My image source is also available on my Github. I use Alpine Linux, OpenJDK 8u92 and a specific plug-in for discovery in a Kubernetes environment.

**Comment by ScubaDrew** [comment]
Thanks for your patience with me Paul! :)

I'm in https://github.com/pires/docker-elasticsearch-kubernetes 

The Dockerfile references 

**FROM** quay.io/pires/docker-elasticsearch:2.3.2

Where can I find the Dockerfile for that base image?

Sorry if I'm missing something and thanks again for the help!

**Comment by pires** [comment]
👍
