### ISSUE TITLE
kubectl logs errors

### ISSUE THREAD

**Issue by TheJena** [pires/kubernetes-elasticsearch-cluster#40]
I have not built my image, just copyed / pasted the "Deploy" section of the readme.

`kubectl version`
> Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
> Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

Everything ok untill:
`kubectl get svc,rc,pods`
> NAME                      CLUSTER-IP   EXTERNAL-IP        PORT(S)    AGE
> elasticsearch             10.0.0.143                      9200/TCP   20m
> elasticsearch-discovery   10.0.0.27    <none>             9300/TCP   20m
> kubernetes                10.0.0.1     <none>             443/TCP    11d
> NAME                      DESIRED      CURRENT            AGE
> es-client                 1            1                  18m
> es-data                   1            1                  18m
> es-master                 1            1                  20m
> NAME                      READY        STATUS             RESTARTS   AGE
> es-client-yduhr           1/1          Running            0          18m
> es-data-950tk             1/1          Running            0          18m
> es-master-h0ble           1/1          Running            0          20m
> k8s-etcd-127.0.0.1        0/1          CrashLoopBackOff   9          11d
> k8s-master-127.0.0.1      4/4          Running            2          47m
> k8s-proxy-127.0.0.1       1/1          Running            0          46m

But `kubectl logs es-master-h0ble` (attached its output) has some errors.

What could I do?

[kubectl_logs.txt](https://github.com/pires/kubernetes-elasticsearch-cluster/files/260975/kubectl_logs.txt)

**Comment by pires** [comment]
This happens because you don't have DNS properly configured on your Kubernetes cluster.
