### ISSUE TITLE
Please update to ES 2.3.3

### ISSUE THREAD

**Issue by haizaar** [pires/kubernetes-elasticsearch-cluster#44]
Hi Paulo,

Can you please update to ES 2.3.3? (It [fixes](https://github.com/elastic/elasticsearch/issues/18089) support for http compression).

Thank you as always!

**Comment by pires** [comment]
Plug-in has been updated and will update no later than tomorrow.

**Comment by haizaar** [comment]
Thanks Paulo!

How can I buy you a beer?
