### ISSUE TITLE
Error from server: the server could not find the requested resource ( pods/log es-master-uvoi6)

### ISSUE THREAD

**Issue by jeremypulcifer** [pires/kubernetes-elasticsearch-cluster#49]
[root@TSTMGTINF01 kubernetes-elasticsearch-cluster]# kubectl log es-master-uvoi6
W0713 15:37:49.279352    8342 cmd.go:219] log is DEPRECATED and will be removed in a future version. Use logs instead.
Error from server: the server could not find the requested resource ( pods/log es-master-uvoi6)

**Comment by pires** [comment]
You should learn how to use `kubectl logs`.
