### ISSUE TITLE
What are minimum capabilities required for containers

### ISSUE THREAD

**Issue by so0k** [pires/kubernetes-elasticsearch-cluster#51]
As suggested in the README, `--privileged` flag is required allowing the containerised ElasticSearch to use `mlockall` and lock the process address space into RAM, preventing any Elasticsearch memory from being swapped out.

is it possible to use more fine grained dropping/adding of capabilities to a minimum set to ensure the cluster stays secure? 

This may be related to: https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/21

**Comment by pires** [comment]
Last time I checked, Docker still didn't support `ulimit` stuff besides what is inherited from the host.
Now, in the context of Kubernetes, [this is still open](https://github.com/kubernetes/kubernetes/issues/3595).

Not sure if there any new [Capabilities](http://kubernetes.io/docs/user-guide/containers/#capabilities) one can use to replace `privileged` mode.
