### ISSUE TITLE
ES_HEAP_SIZE requirements on different nodes types

### ISSUE THREAD

**Issue by andrewmclagan** [pires/kubernetes-elasticsearch-cluster#59]
It seems excessive that each client, master and data node requires a `ES_HEAP_SIZE` of 1GB or more of memory.

Is it only the client and master nodes that require so much memory? or just the clients?

**Comment by pires** [comment]
It is wrong to assume that just because I have set that value as an example default. Feel free to adapt according to your needs.

**Comment by andrewmclagan** [comment]
Sorry i think maybe my question has been misunderstood.

Im asking if the different node types all have the same memory requirements. e.g.
`data, client and master nodes`?

**Comment by andrewmclagan** [comment]
Further though leads me to think only the data node really needs extensive memory as its the only node that performs `storing and indexing` of the documents?

Would that be correct?

**Comment by pires** [comment]
It will depend on your use-case and the load you'll expect to handle to the client-nodes. See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-node.

**Comment by andrewmclagan** [comment]
Is it possible to get some best-practice-advice on this issue, we are now running version 5 with:

* 3 master nodes
* 2 client nodes
* 5 data nodes

`ES_JAVA_OPTS` is set to `-Xms1g -Xmx1g`, across our cluster that sums to 10GB of RAM allocated. In my opinion this seems excessive and could be reduced, the document referenced above does not really detail situations where work is distributed among nodes with different roles: `data`, `master` and `slave`.

Just seeking some general advice, and perhaps this could be useful to the community in general. :-)

**Comment by andrewmclagan** [comment]
To further elaborate, ES docs state that:

> It is important for the stability of the cluster that master-eligible nodes do as little work as possible.

Therefore would it be possible to reduce the heap size for master nodes as they do not require the same resources? Even better for general Kubernetes cluster health as the resources could be allocated to other pods.

Data nodes in the ES docs are described as:

> handle data related operations ... These operations are I/O-, memory-, and CPU-intensive. It is important to monitor these resources and to add more data nodes if they are overloaded.

Therefore these nodes require the most resources.

**Comment by pires** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html

>If there is one resource that you will run out of first, it will likely be memory. Sorting and aggregations can both be memory hungry, so enough heap space to accommodate these is important. Even when the heap is comparatively small, extra memory can be given to the OS filesystem cache. Because many data structures used by Lucene are disk-based formats, Elasticsearch leverages the OS cache to great effect.
>
>A machine with 64 GB of RAM is the ideal sweet spot, but 32 GB and 16 GB machines are also common. Less than 8 GB tends to be counterproductive (you end up needing many, many small machines), and greater than 64 GB has problems

**Comment by pires** [comment]
Also, with a machine with x GB, set Elasticsearch heap size to half of it, giving Lucene (the indexing engine) and the OS enough RAM to operate.

See https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html.

>The default installation of Elasticsearch is configured with a 1 GB heap. For just about every deployment, this number is usually too small. If you are using the default heap values, your cluster is probably configured incorrectly.

> The standard recommendation is to give 50% of the available memory to Elasticsearch heap, while leaving the other 50% free. It won’t go unused; Lucene will happily gobble up whatever is left over.

>If you are not aggregating on analyzed string fields (e.g. you won’t be needing fielddata) you can consider lowering the heap even more. The smaller you can make the heap, the better performance you can expect from both Elasticsearch (faster GCs) and Lucene (more memory for caching).

**Comment by pires** [comment]
Make sure you read the links I shared.
