### ISSUE TITLE
How to deal with nodes folder in ES data

### ISSUE THREAD

**Issue by tsn77130** [pires/kubernetes-elasticsearch-cluster#62]
Hi, 

When I delete / recreate a pod, a new data folder is created on the persistant storage (hostPath), and so the new pod does not find all its indexes. (ex below with 1 & 2 folders)

I have tried to remove node.lock file, but ES creates a new folder anyway.

How could I deal with this ? 

> 
> du -sm  /data/elasticsearch/data/myesdb/nodes/*
> 
> 1       /data/elasticsearch/data/myesdb/nodes/0
> 9813    /data/elasticsearch/data/myesdb/nodes/1
> 3807    /data/elasticsearch/data/myesdb/nodes/2
> 1       /data/elasticsearch/data/myesdb/nodes/3
> 1       /data/elasticsearch/data/myesdb/nodes/4

**Comment by pires** [comment]
See #45

**Comment by pires** [comment]
Nevermind, different problem. I have no answer for you, i'm sorry.

**Comment by tsn77130** [comment]
you don't have this kind of problems ?

**Comment by pires** [comment]
Can you share your `hostPath` declaration?

**Comment by tsn77130** [comment]
volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
        - name: storage
          hostPath:
            path: /data/elasticsearch

**Comment by pires** [comment]
It seems Elasticsearch 2.x changed how it stores data, https://www.elastic.co/blog/found-dive-into-elasticsearch-storage. I'm not sure how to fix this :(

**Comment by pires** [comment]
See #80.
