### ISSUE TITLE
bootstrap check failing

### ISSUE THREAD

**Issue by dvic** [pires/kubernetes-elasticsearch-cluster#72]
I am getting on GKE Kubernetes 1.5.1 the following error:

`bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks`

I solved it by adding the following to the deployments of all node types:
```
        - name: "NETWORK_HOST"
          value: "_site_"
```

Has anyone else encountered this issue?

**Comment by pires** [comment]
@dvic that's not an issue. The env var is exposed exactly so one can override the default value, if needed. In this case, GKE asks for it. 👍

**Comment by pires** [comment]
Weird, by default it is `_site_` See https://github.com/pires/docker-elasticsearch/blob/master/Dockerfile#L33
