### ISSUE TITLE
persistent volume for es-data pods

### ISSUE THREAD

**Issue by hiscal2015** [pires/kubernetes-elasticsearch-cluster#75]
for es-data pods, how can I use persistent volumes like glusterfs, if I use below config, then all es-data pods will write data to the same glusterfs volume, so do I have to create es-data pods separately?

        volumeMounts:
        - name: elasticsearch-storage
          mountPath: /data
      volumes:
      - name: elasticsearch-storage
        glusterfs:
          endpoints: glusterfs-cluster
          path: elasticsearch
          readOnly: false

**Comment by pires** [comment]
You'd need to use StatefulSets, I am to believe.

**Comment by pires** [comment]
See #80.
