### ISSUE TITLE
elastic discovery service cannot sync 

### ISSUE THREAD

**Issue by Fantomatic** [pires/kubernetes-elasticsearch-cluster#78]
Hi, 
Sorry to bother you again, 
I got in my controller manager this when i create the discovery service : 
 Sync default/elasticsearch-discovery failed with Endpoints "elasticsearch-discovery" is invalid: subsets[0].addresses[0].nodeName: Forbidden: Cannot change NodeName for 172.18.0.3 to "HostNodeName".
It also appear that the service is added in my kube-dns. 
I'm using kubernetes 1.5, on 5 rhel7 server. A 3master/2nodes for kube. All in https except for etcd ( which is also in container). I don't have any network overlay (flannel-like). For elastic, it's the version in this repository.  
I understand that my node name is associated with it's own baremetal ip. And that my elasticsearch containers have an ip (172.18.0.3) given, i guess, by kubernetes in the docker network.
I know it's not specific to elasticsearch, as i read a lot of your solutions, you might be able to tell me what i did poorly. 

update : I did try with etcd/flannel in baremetal and it doesn't change a thing

**Comment by pires** [comment]
Unfortunately, I am clueless about what you may be experiencing. Good luck!
