### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by andrewhowdencom** [pires/kubernetes-elasticsearch-cluster#79]
This is a stub to track "create a helm chart" in case someone has already done the necessary work for this. Looking at deploying this for a fairly large log cluster. Requirements are: 

* Need to be able to add data nodes as required. 
* Need to be able to run on k8s 1.5+ (or whatever the most recent k8s is at the time of development). 

I won't get to this for a while. But creating issue anyway!

**Comment by clockworksoul** [comment]
Created. First draft is at https://github.com/clockworksoul/helm-elasticsearch

**Comment by pires** [comment]
Feel free to add instructions to the `README.md` file on how to run your Helm chart and close this issue with your PR.

**Comment by clockworksoul** [comment]
Instructions added with PR https://github.com/pires/kubernetes-elasticsearch-cluster/pull/95

**Comment by pires** [comment]
Fixed by #95.

**Comment by clockworksoul** [comment]
@pires Sincere apologies if I've insulted you (which I think I may have). I have no other way to reach you, and I typed quickly and without thinking.
