### ISSUE TITLE
The Deployment "es-master" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by policy

### ISSUE THREAD

**Issue by xamox** [pires/kubernetes-elasticsearch-cluster#87]
I get the following error when trying to run:
`kubectl create -f es-master.yaml`

`The Deployment "es-master" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by policy`

I'm trying to run this using the LXD local setup with kubernetes without any modifications:
https://kubernetes.io/docs/getting-started-guides/ubuntu/local/

The other services spin up fine (es-discovery and es-svc), it's just when trying to spin up es-master.

Any thoughts as to why I'm getting this error?

Version Info:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-23T22:28:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by pires** [comment]
You need to allow for privileged containers in your cluster by adding `--allow-privileged` to the `kubelet` args.

**Comment by xamox** [comment]
Thanks @pires, and thanks for putting this together as the official k8s example is using an extremely dated version of elasticsearch (1.7).

**Comment by pires** [comment]
Yes, I started it and it used to follow this repo but then maintaining docs in the Kubernetes repo became more complicated and I stopped doing it. I'm sorry if that's not the best for the community at large :-(

**Comment by lordkada** [comment]
I'm experiencing the same problem here :-) 
I am quite sure that kubelets are running with --allow-privileged flag (and this is true for all my nodes) as you can see:

> root@juju-bd405e-9:/# ps axl | grep allow-privileged

> 4     0  2254     1  20   0 695648 87164 futex_ Ssl  ?          1:32 /snap/kubelet/230/kubelet --address 0.0.0.0 **--allow-privileged** --anonymous-auth=false --client-ca-file /root/cdk/ca.crt --cluster-dns 10.152.183.10 --cluster-domain cluster.local --fail-swap-on=false --kubeconfig /root/cdk/kubeconfig --logtostderr --network-plugin cni --port 10250 --tls-cert-file /root/cdk/server.crt --tls-private-key-file /root/cdk/server.key --v 0


but again I get thie error:

> The Deployment "es-master" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

Any idea or suggestion is really appreciated :-)

**Comment by xamox** [comment]
I moved back to testing with minikube as LXD had a lot of other issues for me like consuming 100% cpu when I didn't even have anything deployed in kube, so I don't have any resolution on my side.  They may have fixed this though as I haven't tried using LXD in months.

**Comment by lordkada** [comment]
@xamox yep, I am using it with minikube and it works. I am really curious to test all my software using lxd... I am not experiencing the 100% cpu issue as you did (but this is very funny, because this is the reason why I am moving from minikube 😂😂😂)

**Comment by lordkada** [comment]
**FYI** I have rebuilt my k8s cluster asking my `conjure-up` to allow privileged containers and that error went away... (maybe the last time I missed to set the --allow-privileged for the api-server daemon?!? dunno)

Unfortunately I'm hitting another (unrelated) problem:  
`Error: failed to start container "init-sysctl": Error response from daemon: linux runtime spec devices: lstat /dev/.lxc/proc/1726/fdinfo/12: no such file or directory` :-(

**Comment by nickallevato** [comment]
any luck on this ? I have similar issue on a lab setup.
