### ISSUE TITLE
Shard allocation awareness 

### ISSUE THREAD

**Issue by yukiman76** [pires/kubernetes-elasticsearch-cluster#93]
Would love to have the ability for the ES cluster to know which compute node is currently being used so if the compute host crashes the index would still be able to recover

its a simple change to the es configuration to add an attribute that you would then route on
https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html

**Comment by pires** [comment]
At first I don't think I agree with this. Deploying ES in production should account for [pod anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature). Meaning only one data pod can run on a certain machine.

**Comment by yukiman76** [comment]
interesting but would that only allow for one ES data node for any given compute node, even if better performance would be available by allocation different shards to the same given compute node

**Comment by yukiman76** [comment]
Here is an example, we have 1 index in this cluster and each index
has 5 shards with one replica
logs-2017.04.16 S1,S2,S3,S4,S5  R1,R2,R3,R4,R5

if we have just 2 nodes in a given K8s cluster we could do the following to
increase search responses, and ingest speed (assuming the nodes have the resources to support two containes)

Node1 A
    logs-2017.04.16 S3
    logs-2017.04.16 S5

Node1 B
    logs-2017.04.16 R2
    logs-2017.04.16 S1
    logs-2017.04.16 R4

Node2 A
    logs-2017.04.16 R1
    logs-2017.04.16 S4

Node2 B
    logs-2017.04.16 S2
    logs-2017.04.16 R3
    logs-2017.04.16 R5

**Comment by pires** [comment]
Hmmmm interesting. Care to contribute with a opt-in solution?

**Comment by yukiman76** [comment]
of course :), working on it now

**Comment by yukiman76** [comment]
so i am starting this now, here what has to be done 
elasticsearch.yml 
something like:
if [ ! -z "${SHARD_ALLOCATION_AWARENESS_ATTR}" ]; then
    # this will map to a file like  /etc/hostname => /dockerhostname so reading that file will get the
    #  container hostname
    ES_SHARD_ATTR=`cat ${SHARD_ALLOCATION_AWARENESS_ATTR}`
    echo "node.attr.${SHARD_ALLOCATION_AWARENESS}=${ES_SHARD_ATTR}" >> /etc/elasticsearch/elasticsearch.yml
    echo "cluster.routing.allocation.awareness.attributes: ${SHARD_ALLOCATION_AWARENESS}" >> /etc/elasticsearch/elasticsearch.yml
fi 
so do, but it will have to added to the project https://github.com/pires/docker-elasticsearch unless you have another idea ?

**Comment by yukiman76** [comment]
Please see PR https://github.com/pires/docker-elasticsearch/pull/36, this can be closed in this repo

**Comment by pires** [comment]
Merged and available as of `5.3.2.`. Care to provide some instructions to the `README.md` file on how to use this?

**Comment by yukiman76** [comment]
Sure, let me do a full reset to the dev env and document the process

**Comment by pires** [comment]
Done! Thanks @yukiman76.
