### ISSUE TITLE
Upgrade Elasticsearch to version 5.4.0.

### ISSUE THREAD

**Issue by ssouris** [pires/kubernetes-elasticsearch-cluster#97]
With X-Pack and Kibana you can get a good visualization of your cluster state without any hussle and the new 5.4 brings creation of machine learning jobs through X-Pack (in beta mode) over your data.

It would be really really awesome.

**Comment by pires** [comment]
The 5.4 image is available. You can do it yourself without waiting on me to update this repo ;)

**Comment by ssouris** [comment]
@pires thanks :)

**Comment by pires** [comment]
See #99, I've added info on how to install the plug-ins ;)

**Comment by ssouris** [comment]
Nice seems smart to configure the plugins this way 👍
